# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/product_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductWindow(object):
    def setupUi(self, ProductWindow):
        ProductWindow.setObjectName("ProductWindow")
        ProductWindow.resize(906, 669)
        ProductWindow.setMinimumSize(QtCore.QSize(900, 600))
        ProductWindow.setStyleSheet("background-color: white; color: black;")
        self.centralwidget = QtWidgets.QWidget(ProductWindow)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(460, 25, 320, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(800, 15, 80, 35))
        self.logout_button.setObjectName("logout_button")
        self.orders_button = QtWidgets.QPushButton(self.centralwidget)
        self.orders_button.setGeometry(QtCore.QRect(10, 50, 100, 35))
        self.orders_button.setObjectName("orders_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(160, 50, 130, 35))
        self.add_button.setObjectName("add_button")
        self.search_label = QtWidgets.QLabel(self.centralwidget)
        self.search_label.setGeometry(QtCore.QRect(10, 100, 50, 25))
        self.search_label.setObjectName("search_label")
        self.search_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_edit.setGeometry(QtCore.QRect(65, 100, 200, 25))
        self.search_edit.setObjectName("search_edit")
        self.sort_label = QtWidgets.QLabel(self.centralwidget)
        self.sort_label.setGeometry(QtCore.QRect(270, 100, 90, 25))
        self.sort_label.setObjectName("sort_label")
        self.sort_combo = QtWidgets.QComboBox(self.centralwidget)
        self.sort_combo.setGeometry(QtCore.QRect(375, 100, 150, 25))
        self.sort_combo.setObjectName("sort_combo")
        self.sort_combo.addItem("")
        self.sort_combo.addItem("")
        self.sort_combo.addItem("")
        self.sort_combo.addItem("")
        self.sort_combo.addItem("")
        self.scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_area.setGeometry(QtCore.QRect(10, 140, 880, 520))
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.products_container = QtWidgets.QWidget()
        self.products_container.setGeometry(QtCore.QRect(0, 0, 878, 518))
        self.products_container.setObjectName("products_container")
        self.scroll_area.setWidget(self.products_container)
        ProductWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProductWindow)
        QtCore.QMetaObject.connectSlotsByName(ProductWindow)

    def retranslateUi(self, ProductWindow):
        _translate = QtCore.QCoreApplication.translate
        ProductWindow.setWindowTitle(_translate("ProductWindow", "ООО \"Обувь\" - Управление товарами"))
        self.user_label.setText(_translate("ProductWindow", "ФИО пользователя"))
        self.logout_button.setText(_translate("ProductWindow", "Выход"))
        self.orders_button.setText(_translate("ProductWindow", "Заказы"))
        self.add_button.setText(_translate("ProductWindow", "Добавить товар"))
        self.search_label.setText(_translate("ProductWindow", "Поиск:"))
        self.search_edit.setPlaceholderText(_translate("ProductWindow", "Введите текст..."))
        self.sort_label.setText(_translate("ProductWindow", "Сортировка:"))
        self.sort_combo.setItemText(0, _translate("ProductWindow", "По названию"))
        self.sort_combo.setItemText(1, _translate("ProductWindow", "По цене (возр)"))
        self.sort_combo.setItemText(2, _translate("ProductWindow", "По цене (убыв)"))
        self.sort_combo.setItemText(3, _translate("ProductWindow", "По количеству"))
        self.sort_combo.setItemText(4, _translate("ProductWindow", "По скидке"))
